Plat 175 await helper logic update
jembi/platform-await-helper pull request #1
Opened 2022-03-23 13:52 UTC by Mark-Labuschagne

2022-03-31 08:59 UTC, MattyJ007 requested changes
Good job splitting this out.

One change we need though for consistency is the tag.
When doing Semver versioning we need three values. Enjoy: https://semver.org/
Also, you'll need to push a tag and create a release.

Extra points for setting up a quick dockerhub release using github actions

2022-03-31 08:59 UTC, MattyJ007 commented on awaitHelper.sh
> +ResponseOK="false"
Let's tell the user that the file has started something:

`echo "Waiting for $@"`

2022-03-31 10:22 UTC, Mark-Labuschagne commented on awaitHelper.sh
> +    elif [ "$(($currentTime - $StartTime))" -ge 130 ] && [ $Warned = "true" ]; then
130 seconds ensures that this function won't end before the swarm.sh logic in IOL openhim checking for the container running this file ends. Giving it the best chance of succeeding. With that being said, because of the logic in IOL/swarm.sh, it would never end before IOL's timeout check ends, even with this value set to 120. So, I'll set it back to 120 for the sake of consistency.

2022-03-31 10:24 UTC, Mark-Labuschagne commented on awaitHelper.sh
> +ResponseOK="false"
Yip yip, way cleaner the way you suggest.

2022-03-31 13:26 UTC, Mark-Labuschagne commented
When merged, this PR needs to be marked as a minor version (0.1.0). The major version can be pushed with when [jembi/platform](https://github.com/jembi/platform) has it's first major release. A github action has been introduced to push to dockerhub on release or version update.

2022-04-01 07:20 UTC, MattyJ007 approved these changes

2022-04-01 07:20 UTC, merged